# Simulation parameters
VERSION: 2.0
DT: 2.5  # time passing between consecutive steps (relevant for age and movement)
NUM_FRAMES: 200  # the actual number of steps = NUM_FRAMES * UPDATE_ANIMATION_INTERVAL

# key is frame number and value is num steps per frame from this frame onward
NUM_STEPS_FROM_FRAME_DICT: { 0: 200,
                             5: 100
}

FRAME_INTERVAL: 75  # interval between frames in animation [in ms]
STATUS_EVERY_STEP: True  # choose if to update every step or every frame
UPDATE_KDTREE_INTERVAL: 120  # update the kdtree every n steps
DEBUG_MODE: False  # breakpoint in update_func after each frame (not step!)
REBALANCE: True
PURGE_POP_PERCENTAGE: 0.75  # percentage of MAX_NUM_CREATURES to stuck simulation

# Purge parameters
DO_PURGE: True
PURGE_FRAME_FREQUENCY: 50  # do purge every PURGE_FRAME_FREQUENCY frames
PURGE_PERCENTAGE: 0.1  # percentage out of MAX_NUM_CREATURES to do purge
PURGE_SPEED_THRESHOLD: 0.1  # if the creature's speed is below this threshold at first reproduction, it will be removed

# Environment parameters
ENV_PATH: Penvs/Env8.png
BOUNDARY_CONDITION: 'zero'  # what to do with the velocity on the boundaries - 'mirror' or 'zero'
MAX_GRASS_NUM: 100
GRASS_GENERATION_RATE: 5  # if exceeding MAX_GRASS_NUM replace GRASS_GENERATION_RATE grass points
GRASS_GROWTH_CHANCE: 0.1  # changed: 0.5  # maybe will be useful to create droughts
MAX_LEAVES_NUM: 50
LEAVES_GENERATION_RATE: 0  # if exceeding MAX_LEAVES_NUM replace LEAVES_GENERATION_RATE grass points
LEAVES_GROWTH_CHANCE: 0.5  # maybe will be useful to create droughts

# Food parameters
LEAF_HEIGHT: 10
FOOD_DISTANCE_THRESHOLD: 75

# Energy parameters
INIT_MAX_ENERGY: 20000  # maybe useful for maturity test before reproduction
REPRODUCTION_ENERGY: 4000 # changed: 5000  # energy cost of reproduction
MIN_LIFE_ENERGY: 5000  # energy to be left after reproduction
GRASS_ENERGY: 2000
LEAF_ENERGY: 2000

CHANCE_TO_HERBIVORE: 0.5

INIT_HERBIVORE_DIGEST_DICT: { 'grass': 1,
                              'leaf': 0,
                              'creature': 0 }

INIT_CARNIVORE_DIGEST_DICT: { 'grass': 0,
                              'leaf': 0,
                              'creature': 1 }

# Creatures parameters
NUM_CREATURES: 500  # init size of population
MAX_NUM_CREATURES: 1500
INIT_MAX_AGE:  10000 # changed: 60000  # [sec] step_number * config.DT
ADOLESCENCE_AGE_FRACTION: 0.05  # [0-1] fraction of INIT_MAX_AGE for adulthood
REPRODUCTION_COOLDOWN: 300  # [sec] minimal time between reproduction events
INIT_MAX_MASS: 10  # [kg]
INIT_MAX_HEIGHT: 1  # [m]
INIT_MAX_STRENGTH: 5  # [N]
MAX_SPEED: 2.5  # [m/sec] maximum speed of the creature

# Eyes parameters
# Define eye parameters: (angle_offset in radians, aperture in radians)
# eyes_params: ((np.radians(30), np.radians(45)),(np.radians(-30), np.radians(45)))
EYE_CHANNEL: [ 'grass' , 'creature' ]  # ['grass', 'leaves', 'water', 'creature']
EYES_PARAMS: [
  [ 0, 90 ]
]  # list of lists - angle_offset (degrees), aperture (degrees)
VISION_LIMIT: 1000  # maximum distance that the creature can see
NOISE_STD: 0.5  # gaussian noise for vision - currently not in use

# Brain parameters
BRAIN_TYPE: 'graphic_brain'  # 'fully_connected_brain' or 'graphic_brain'
# d_velocity and d_angle
OUTPUT_SIZE: 2
NORM_INPUT: [ 1, 1, 1 ]

# Mutations
MUTATION_CHANCE: 0.3  # number between 0-1 indicating chance of trait to be mutated
STD_MUTATION_FACTORS: { 'color': 0.1,  # +-in each RGB color

                        'max_age': 2,
                        'max_mass': 1,
                        'max_height': 1,
                        'max_strength': 1,
                        'max_speed': 0.1,
                        'max_energy': 0,

                        'digest_dict': { 'grass': 0.1, 'leaf': 0.1, 'creature': 0.05 },
                        'reproduction_energy': 0,

                        'eyes_params': 5,  # +-degrees for each eye for angle and width
                        'vision_limit': 4, }

MUTATION_FC_BRAIN: { 'layer_addition': 0.1,
                     'modify_weights': 0.2,
                     'modify_layer': 0.2,
                     'modify_activation': 0.1 }

MUTATION_GRAPH_BRAIN: { 'add_node': 0.1,
                        'remove_node': 0.1,
                        'modify_edges': 0.7,  # chance to perform a change to the weights
                        'modify_edges_percentage': 0.5,  # percentage of edges to change
                        'add_edge': 0.3,
                        'remove_edge': 0.1,
                        'change_activation': 0.1,
                        'forget_magnitude': 10,
                        'add_loop': 0.2,
                        'break_edge': 0.5 }

# Filepaths
FFMPEG_PATH: ffmpeg-2025-02-20-git-bc1a3bfd2c-essentials_build\bin\ffmpeg.exe


